# Generated by Django 2.2.5 on 2020-04-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20200409_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults\\default_avatar.png', upload_to='post_images'),
        ),
    ]
