# Generated by Django 2.2.5 on 2020-04-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20200409_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='defaults\\default_meal.png', upload_to='post_images'),
        ),
    ]
