# Generated by Django 3.0.3 on 2020-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='defaults\\default_avatar.png', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currentWeight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='desiredWeight',
            field=models.IntegerField(blank=True),
        ),
    ]
